pipeline {
    agent { label 'OPENJDK' }
    stages {
        // stage('pulling image from opensource') {
        //     steps {
        //         sh """ docker image pull nginx 
        //             docker image tag nginx fortestingmyself.jfrog.io/myrepo/nginx:1.0
        //             docker image push fortestingmyself.jfrog.io/myrepo/nginx:1.0"""
        //     }
        // }
        stage ('test image ') {
            steps{
                sh """ docker image pull jenkins/jenkins
                docker image tag jenkins/jenkins fortestingmyself.jfrog.io/myrepo/jenkins/jenkins
                docker push fortestingmyself.jfrog.io/myrepo/jenkins/jenkins"""
            }
        }
    }
}